import Foundation

/**
 Split a line that is wider than the model window into pieces that each fit it.

 A line wider than the window is otherwise SQUEEZED into it — scaled by height,
 then clamped to the target width, which compresses the glyphs horizontally.
 Measured over 240 rendered Mon lines wide enough to need the choice, median 3
 tiles at the model height, one harness with only the graph swapped:

     v2     squeezed 0.0676   tiled 0.0758   CER
     v3.5   squeezed 0.1434   tiled 0.0795   CER

 This app ships v3.5 (`d3d9d5e`), so it was on the worse side of that gap.
 Tiling hurts v2, so a build repinned to `a51be11` must stop calling this.

 REMEASURED 2026-08-22, and the figures above did not reproduce.
 `mon_OCR/eval/tiling-ab-2026-08-22.md` scored 201 rendered lines through both
 the Python arms and the Rust binding and found the answer is width-dependent:
 squeezing wins at 2 tiles, the two are at parity at 3, and tiling wins from 4
 tiles up, reaching 20x-36x by 6 where squeezing exceeds 0.83 CER. At median 3
 tiles -- the population the numbers above were taken on -- there is no tiling
 advantage. Tiling stays the default because its downside is bounded and
 squeezing's is not, so this is a safety net rather than a general win.

 Ported from monocr-onnx `python/monocr_onnx/segmenter.py` (`tile_line`,
 `cut_column`); the constants below are the same, so the two produce identical
 cuts on the same input. `LineTilingTests` checks that against fixtures
 generated by running the Python function itself.
 */
nonisolated enum LineTiler {

    /// Where a tile may be cut, as a fraction of the tile width, searching
    /// backwards from the ideal boundary. 0.12 of a 1024px window is ~123px,
    /// roughly two Mon glyphs — wide enough to find a gap, narrow enough that
    /// tiles stay near full width.
    static let cutSearchFraction = 0.12

    /// A column counts as carrying ink below this grey value.
    static let cutInkThreshold: UInt8 = 250

    /**
     Where to end a tile that starts at `x0` and may not pass `ideal`.

     Cutting at exactly `ideal` lands wherever the arithmetic falls, which is
     usually the middle of a glyph. Both halves keep their pixels, so a coverage
     check still passes, but the model reads each half as a whole character and
     one glyph becomes two — upstream this showed up as `ဗော်` read back as
     `ဗေဗိာ်`.

     So search backwards from `ideal` for a column of white. A tile may only get
     narrower, never wider, or it stops fitting the model window. Returns `ideal`
     unchanged when there is no gap to cut at, which is the honest outcome for a
     continuous script: a known-bad seam beats an overflowing tile.

     `x0`, `ideal` and `cropW` are measured from the left edge of `segment`, not
     of the page. Exposed rather than private because a wrong tile width does not
     say whether the cut search or the tiling loop is at fault, and the fixtures
     carry probes that pin the cut search on its own.
     */
    static func cutColumn(
        page: GreyImage,
        segment: LineSegment,
        x0: Int,
        ideal: Int,
        cropW: Int
    ) -> Int {
        if ideal >= cropW { return cropW }

        let window = max(1, Int(Double(ideal - x0) * cutSearchFraction))
        let lo = max(x0 + 1, ideal - window)
        if lo >= ideal { return ideal }

        // Ink per column across the band, counted on the page buffer directly.
        // The pixels are already here, and a round trip through a crop would
        // resample them and move the cut.
        var best = lo
        var bestInk = Int.max
        var rightmostBlank = -1

        for x in lo..<ideal {
            var ink = 0
            for y in 0..<segment.height {
                let px = segment.x + x
                let py = segment.y + y
                guard page.contains(x: px, y: py) else { continue }
                if page.pixel(x: px, y: py) < cutInkThreshold { ink += 1 }
            }
            // Prefer a truly empty column, and the rightmost one, so tiles stay
            // as wide as the window allows. Otherwise the lightest column wins,
            // and the first of a tie, which is what numpy's argmin returns.
            if ink == 0 { rightmostBlank = x }
            if ink < bestInk {
                bestInk = ink
                best = x
            }
        }

        return rightmostBlank >= 0 ? rightmostBlank : best
    }

    /**
     Split one line into pieces that each fit the model window.

     Returns the segment unchanged when it already fits after being scaled to
     `targetHeight`. Otherwise cuts at whitespace columns and returns the pieces
     left to right, in page coordinates. The pieces are read separately and
     joined with no separator: the cut falls inside a word, so a space there
     would be wrong.
     */
    static func tileLine(
        page: GreyImage,
        segment: LineSegment,
        targetHeight: Int,
        targetWidth: Int
    ) -> [LineSegment] {
        if segment.height <= 0 || segment.width <= 0 { return [segment] }

        let scale = Double(targetHeight) / Double(segment.height)
        if Int(Double(segment.width) * scale) <= targetWidth { return [segment] }

        let tileWidthSource = max(1, Int(Double(targetWidth) / scale))
        var tiles = [LineSegment]()
        var x0 = 0

        while x0 < segment.width {
            let ideal = min(x0 + tileWidthSource, segment.width)
            // Structural guard, not a tuning knob: cutColumn can only return a
            // value in (x0, ideal], but if it ever returned x0 this loop would
            // spin forever on a page. One pixel of forced progress bounds it.
            let x1 = max(
                cutColumn(page: page, segment: segment, x0: x0, ideal: ideal, cropW: segment.width),
                x0 + 1
            )
            tiles.append(
                LineSegment(x: segment.x + x0, y: segment.y, width: x1 - x0, height: segment.height)
            )
            x0 = x1
        }

        return tiles
    }
}
