import { describe, expect, it } from 'vitest';

import fixture from '../../../../shared/segmentation-fixtures/tiling-cases.json';
import { cutColumn, looksLikeALine, segmentLines, tileLine } from './segmentation';

/**
 * Tiling parity with the Python binding.
 *
 * `tileLine` is a port of `tile_line`/`cut_column` in monocr-onnx
 * `python/monocr_onnx/segmenter.py`. Tiling was measured against squeezing on
 * that implementation, so a port that cuts at different columns is not the thing
 * the measurement applies to — which is why these tests pin cut positions and not
 * just tile counts.
 *
 * This block used to justify tiling with `CER 0.1434 squeezed against 0.0795
 * tiled`. Retired 2026-08-22: that harness was never committed and the figures
 * do not reproduce. The live measurement is
 * `mon_OCR/eval/tiling-ab-2026-08-22.md` over 201 rendered lines, and it is
 * width-dependent — squeezing wins at 2 tiles, the two arms are level at 3, and
 * tiling wins from 4 up. Tiling is still the default because its downside is
 * bounded and squeezing's is not, which is a different argument from the one
 * this comment used to make.
 *
 * The cases now come from `shared/segmentation-fixtures/tiling-cases.json`,
 * generated by running the Python function itself. This file used to carry its
 * own copy of the expected widths, and so does every other port — four
 * hand-maintained copies of one contract is how ports drift apart. Android, iOS
 * and Rust read the same file. Regenerate it rather than editing a number here.
 */
const TARGET_H = fixture.target_height;
const TARGET_W = fixture.target_width;

/** Rebuild a fixture case's ink rule. Must match the generator exactly. */
function inkRule(kind: string, modulus: number): (x: number) => boolean {
	switch (kind) {
		case 'mod_eq':
			return (x) => x % modulus === 0;
		case 'mod_ne':
			return (x) => x % modulus !== 0;
		case 'solid':
			return () => true;
		case 'blank':
			return () => false;
		default:
			throw new Error(`unknown ink rule: ${kind}`);
	}
}

/** White canvas with full-height black bars wherever `inked(x)` holds. */
function page(w: number, h: number, inked: (x: number) => boolean): ImageData {
	const data = new Uint8ClampedArray(w * h * 4).fill(255);
	for (let x = 0; x < w; x++) {
		if (!inked(x)) continue;
		for (let y = 0; y < h; y++) {
			const o = (y * w + x) * 4;
			data[o] = data[o + 1] = data[o + 2] = 0;
		}
	}
	return { width: w, height: h, data, colorSpace: 'srgb' } as ImageData;
}

const CASES = fixture.cases.map((c) => ({
	name: c.name,
	w: c.width,
	h: c.height,
	inked: inkRule(c.ink.kind, c.ink.modulus),
	widths: c.expected_tile_widths
}));

/** The case with several tiles and clean gaps, used by the behavioural tests. */
const MULTI_TILE = CASES.find((c) => c.name === 'a gap inside the search window')!;

describe('tileLine matches the Python binding it was ported from', () => {
	for (const c of CASES) {
		it(c.name, () => {
			const img = page(c.w, c.h, c.inked);
			const tiles = tileLine(img, { x: 0, y: 0, width: c.w, height: c.h }, TARGET_H, TARGET_W);

			expect(tiles.map((t) => t.width)).toEqual(c.widths);
		});
	}

	// The partition property is what stops tiling losing or duplicating text, so
	// it is asserted on every case rather than one representative.
	for (const c of CASES) {
		it(`partitions exactly: ${c.name}`, () => {
			const tiles = tileLine(
				page(c.w, c.h, c.inked),
				{ x: 0, y: 0, width: c.w, height: c.h },
				TARGET_H,
				TARGET_W
			);

			let x = 0;
			for (const t of tiles) {
				expect(t.x).toBe(x);
				expect(t.width).toBeGreaterThan(0);
				x += t.width;
			}
			expect(x).toBe(c.w);
		});
	}

	it('covers the line exactly, with no gap and no overlap', () => {
		const c = MULTI_TILE;
		const tiles = tileLine(
			page(c.w, c.h, c.inked),
			{ x: 0, y: 0, width: c.w, height: c.h },
			TARGET_H,
			TARGET_W
		);

		// Dropping or double-reading a strip is how tiling silently loses text.
		let x = 0;
		for (const t of tiles) {
			expect(t.x).toBe(x);
			x += t.width;
		}
		expect(x).toBe(c.w);
	});

	it('offsets tiles by the segment origin, not the crop', () => {
		// processLine is handed page coordinates, so a line part-way down a page
		// must not have its tiles reported from 0.
		const c = MULTI_TILE;
		const tiles = tileLine(
			page(c.w, c.h, c.inked),
			{ x: 40, y: 25, width: c.w - 40, height: c.h - 25 },
			TARGET_H,
			TARGET_W
		);

		expect(tiles[0].x).toBe(40);
		expect(tiles.every((t) => t.y === 25)).toBe(true);
	});

	// Pins the cut search on its own. Without these, a wrong tile width does not
	// say whether the search window or the tiling loop is at fault.
	for (const p of fixture.cut_column_probes) {
		it(`cutColumn: ${p.name}`, () => {
			const img = page(p.width, p.height, inkRule(p.ink.kind, p.ink.modulus));
			const cut = cutColumn(
				img,
				{ x: 0, y: 0, width: p.width, height: p.height },
				p.x0,
				p.ideal,
				p.width
			);

			expect(cut).toBe(p.expected_cut);
		});
	}

	it('always advances, so a pathological line cannot spin forever', () => {
		// cut_column can only return a value in (x0, ideal], but the guard behind
		// that is structural. A one-pixel-wide tall line is the degenerate input.
		const tiles = tileLine(
			page(4, 4000, () => true),
			{ x: 0, y: 0, width: 4, height: 4000 },
			TARGET_H,
			TARGET_W
		);

		expect(tiles.length).toBeGreaterThan(0);
		expect(tiles.every((t) => t.width >= 1)).toBe(true);
	});
});

/**
 * The fused-block flag.
 *
 * Cases and reasons are lifted verbatim from `mon_OCR`
 * `tests/test_segmenter.py::test_a_fused_block_is_not_a_line`, so this port and the
 * canonical implementation are pinned to the same evidence rather than to two
 * separately chosen rules. It takes both axes: page fraction alone rejects the
 * first two, which are genuine single lines filling their own image, and aspect
 * alone rejects the third, a short word taller than it is wide.
 */
describe('looksLikeALine', () => {
	const cases: [number, number, number, boolean, string][] = [
		[1024, 160, 160, true, 'a single-line crop is 100% of its own image'],
		[693, 128, 128, true, 'the digit strip: its band is 693px wide, not the full 1024'],
		[200, 220, 2200, true, 'a short word on a page is taller than it is wide'],
		[1000, 339, 1524, true, 'the tallest band on a readable screenshot'],
		[1200, 493, 760, false, 'the fused band that returned confident fiction'],
		[1200, 476, 760, false, 'its neighbour on the same photo'],
		[2048, 1366, 1366, false, 'a whole page returned as one band']
	];

	for (const [width, height, page, expected, why] of cases) {
		it(`${width}x${height} on a ${page}px page -> ${expected}: ${why}`, () => {
			expect(looksLikeALine({ x: 0, y: 0, width, height }, page)).toBe(expected);
		});
	}

	it('a degenerate box is not a line', () => {
		expect(looksLikeALine({ x: 0, y: 0, width: 100, height: 0 }, 100)).toBe(false);
		expect(looksLikeALine({ x: 0, y: 0, width: 100, height: 50 }, 0)).toBe(false);
	});

	it('segmentLines flags every segment it returns', () => {
		// One wide dark band on a white page: a plain, unambiguous line.
		const w = 400;
		const h = 200;
		const data = new Uint8ClampedArray(w * h * 4).fill(255);
		for (let y = 80; y < 120; y++) {
			for (let x = 20; x < 380; x += 8) {
				const i = (y * w + x) * 4;
				data[i] = data[i + 1] = data[i + 2] = 0;
			}
		}
		const segments = segmentLines({ width: w, height: h, data } as ImageData);
		expect(segments.length).toBeGreaterThan(0);
		for (const seg of segments) {
			expect(typeof seg.lineShaped).toBe('boolean');
		}
	});
});
