import { describe, expect, it } from 'vitest';

import fixture from '../../../../shared/segmentation-fixtures/tiling-cases.json';
import {
	backgroundIsDark,
	cutColumn,
	looksLikeALine,
	mergeRuns,
	normalizePagePolarity,
	segmentLines,
	tileLine
} from './segmentation';

/**
 * Tiling parity with the Python binding.
 *
 * `tileLine` is a port of `tile_line`/`cut_column` in monocr-onnx
 * `python/monocr_onnx/segmenter.py`. Tiling was measured against squeezing on
 * that implementation, so a port that cuts at different columns is not the thing
 * the measurement applies to — which is why these tests pin cut positions and not
 * just tile counts.
 *
 * This block used to justify tiling with `CER 0.1434 squeezed against 0.0795
 * tiled`. Retired 2026-08-22: that harness was never committed and the figures
 * do not reproduce. The live measurement is
 * `mon_OCR/eval/tiling-ab-2026-08-22.md` over 201 rendered lines, and it is
 * width-dependent — squeezing wins at 2 tiles, the two arms are level at 3, and
 * tiling wins from 4 up. Tiling is still the default because its downside is
 * bounded and squeezing's is not, which is a different argument from the one
 * this comment used to make.
 *
 * The cases now come from `shared/segmentation-fixtures/tiling-cases.json`,
 * generated by running the Python function itself. This file used to carry its
 * own copy of the expected widths, and so does every other port — four
 * hand-maintained copies of one contract is how ports drift apart. Android, iOS
 * and Rust read the same file. Regenerate it rather than editing a number here.
 */
const TARGET_H = fixture.target_height;
const TARGET_W = fixture.target_width;

/** Rebuild a fixture case's ink rule. Must match the generator exactly. */
function inkRule(kind: string, modulus: number): (x: number) => boolean {
	switch (kind) {
		case 'mod_eq':
			return (x) => x % modulus === 0;
		case 'mod_ne':
			return (x) => x % modulus !== 0;
		case 'solid':
			return () => true;
		case 'blank':
			return () => false;
		default:
			throw new Error(`unknown ink rule: ${kind}`);
	}
}

/** White canvas with full-height black bars wherever `inked(x)` holds. */
function page(w: number, h: number, inked: (x: number) => boolean): ImageData {
	const data = new Uint8ClampedArray(w * h * 4).fill(255);
	for (let x = 0; x < w; x++) {
		if (!inked(x)) continue;
		for (let y = 0; y < h; y++) {
			const o = (y * w + x) * 4;
			data[o] = data[o + 1] = data[o + 2] = 0;
		}
	}
	return { width: w, height: h, data, colorSpace: 'srgb' } as ImageData;
}

const CASES = fixture.cases.map((c) => ({
	name: c.name,
	w: c.width,
	h: c.height,
	inked: inkRule(c.ink.kind, c.ink.modulus),
	widths: c.expected_tile_widths
}));

/** The case with several tiles and clean gaps, used by the behavioural tests. */
const MULTI_TILE = CASES.find((c) => c.name === 'a gap inside the search window')!;

describe('tileLine matches the Python binding it was ported from', () => {
	for (const c of CASES) {
		it(c.name, () => {
			const img = page(c.w, c.h, c.inked);
			const tiles = tileLine(img, { x: 0, y: 0, width: c.w, height: c.h }, TARGET_H, TARGET_W);

			expect(tiles.map((t) => t.width)).toEqual(c.widths);
		});
	}

	// The partition property is what stops tiling losing or duplicating text, so
	// it is asserted on every case rather than one representative.
	for (const c of CASES) {
		it(`partitions exactly: ${c.name}`, () => {
			const tiles = tileLine(
				page(c.w, c.h, c.inked),
				{ x: 0, y: 0, width: c.w, height: c.h },
				TARGET_H,
				TARGET_W
			);

			let x = 0;
			for (const t of tiles) {
				expect(t.x).toBe(x);
				expect(t.width).toBeGreaterThan(0);
				x += t.width;
			}
			expect(x).toBe(c.w);
		});
	}

	it('covers the line exactly, with no gap and no overlap', () => {
		const c = MULTI_TILE;
		const tiles = tileLine(
			page(c.w, c.h, c.inked),
			{ x: 0, y: 0, width: c.w, height: c.h },
			TARGET_H,
			TARGET_W
		);

		// Dropping or double-reading a strip is how tiling silently loses text.
		let x = 0;
		for (const t of tiles) {
			expect(t.x).toBe(x);
			x += t.width;
		}
		expect(x).toBe(c.w);
	});

	it('offsets tiles by the segment origin, not the crop', () => {
		// processLine is handed page coordinates, so a line part-way down a page
		// must not have its tiles reported from 0.
		const c = MULTI_TILE;
		const tiles = tileLine(
			page(c.w, c.h, c.inked),
			{ x: 40, y: 25, width: c.w - 40, height: c.h - 25 },
			TARGET_H,
			TARGET_W
		);

		expect(tiles[0].x).toBe(40);
		expect(tiles.every((t) => t.y === 25)).toBe(true);
	});

	// Pins the cut search on its own. Without these, a wrong tile width does not
	// say whether the search window or the tiling loop is at fault.
	for (const p of fixture.cut_column_probes) {
		it(`cutColumn: ${p.name}`, () => {
			const img = page(p.width, p.height, inkRule(p.ink.kind, p.ink.modulus));
			const cut = cutColumn(
				img,
				{ x: 0, y: 0, width: p.width, height: p.height },
				p.x0,
				p.ideal,
				p.width
			);

			expect(cut).toBe(p.expected_cut);
		});
	}

	it('always advances, so a pathological line cannot spin forever', () => {
		// cut_column can only return a value in (x0, ideal], but the guard behind
		// that is structural. A one-pixel-wide tall line is the degenerate input.
		const tiles = tileLine(
			page(4, 4000, () => true),
			{ x: 0, y: 0, width: 4, height: 4000 },
			TARGET_H,
			TARGET_W
		);

		expect(tiles.length).toBeGreaterThan(0);
		expect(tiles.every((t) => t.width >= 1)).toBe(true);
	});
});

/**
 * The fused-block flag.
 *
 * Cases and reasons are lifted verbatim from `mon_OCR`
 * `tests/test_segmenter.py::test_a_fused_block_is_not_a_line`, so this port and the
 * canonical implementation are pinned to the same evidence rather than to two
 * separately chosen rules. It takes both axes: page fraction alone rejects the
 * first two, which are genuine single lines filling their own image, and aspect
 * alone rejects the third, a short word taller than it is wide.
 */
describe('looksLikeALine', () => {
	const cases: [number, number, number, boolean, string][] = [
		[1024, 160, 160, true, 'a single-line crop is 100% of its own image'],
		[693, 128, 128, true, 'the digit strip: its band is 693px wide, not the full 1024'],
		[200, 220, 2200, true, 'a short word on a page is taller than it is wide'],
		[1000, 339, 1524, true, 'the tallest band on a readable screenshot'],
		[1200, 493, 760, false, 'the fused band that returned confident fiction'],
		[1200, 476, 760, false, 'its neighbour on the same photo'],
		[2048, 1366, 1366, false, 'a whole page returned as one band']
	];

	for (const [width, height, page, expected, why] of cases) {
		it(`${width}x${height} on a ${page}px page -> ${expected}: ${why}`, () => {
			expect(looksLikeALine({ x: 0, y: 0, width, height }, page)).toBe(expected);
		});
	}

	it('a degenerate box is not a line', () => {
		expect(looksLikeALine({ x: 0, y: 0, width: 100, height: 0 }, 100)).toBe(false);
		expect(looksLikeALine({ x: 0, y: 0, width: 100, height: 50 }, 0)).toBe(false);
	});

	it('segmentLines flags every segment it returns', () => {
		// One wide dark band on a white page: a plain, unambiguous line.
		const w = 400;
		const h = 200;
		const data = new Uint8ClampedArray(w * h * 4).fill(255);
		for (let y = 80; y < 120; y++) {
			for (let x = 20; x < 380; x += 8) {
				const i = (y * w + x) * 4;
				data[i] = data[i + 1] = data[i + 2] = 0;
			}
		}
		const segments = segmentLines({ width: w, height: h, data } as ImageData);
		expect(segments.length).toBeGreaterThan(0);
		for (const seg of segments) {
			expect(typeof seg.lineShaped).toBe('boolean');
		}
	});
});

/**
 * Page polarity, decided once.
 *
 * Cases mirror iOS `PageNormalizerTests`. The one that matters is
 * `segmentationFindsTextNotGapsOnADarkPage`: it demonstrates the defect this
 * function exists for, rather than only testing the function in isolation.
 */
describe('page polarity', () => {
	/** A page of `bg`, with evenly spaced full-height bars of `ink` in one band. */
	function page(w: number, h: number, bg: number, ink: number, band: [number, number]) {
		const data = new Uint8ClampedArray(w * h * 4);
		for (let i = 0; i < w * h; i++) {
			const o = i * 4;
			data[o] = data[o + 1] = data[o + 2] = bg;
			data[o + 3] = 255;
		}
		for (let y = band[0]; y < band[1]; y++) {
			for (let x = 20; x < w - 20; x += 8) {
				const o = (y * w + x) * 4;
				data[o] = data[o + 1] = data[o + 2] = ink;
			}
		}
		return { width: w, height: h, data } as ImageData;
	}

	it('detects a dark background', () => {
		expect(backgroundIsDark(page(200, 200, 20, 240, [80, 120]))).toBe(true);
	});

	it('leaves a light background alone', () => {
		const light = page(200, 200, 250, 10, [80, 120]);
		expect(backgroundIsDark(light)).toBe(false);
		expect(normalizePagePolarity(light)).toBe(false);
	});

	it('a dark page comes out dark ink on white', () => {
		const dark = page(200, 200, 20, 240, [80, 120]);
		expect(normalizePagePolarity(dark)).toBe(true);
		// A corner was background (20) and is now paper (235).
		expect(dark.data[0]).toBe(235);
		// The alpha channel is untouched.
		expect(dark.data[3]).toBe(255);
	});

	it('samples corners, not a global mean', () => {
		// Light paper, but the middle 60% is solid ink — a global mean would call this
		// dark. The corners are what make it light, which is the reason for the patches.
		const w = 200;
		const h = 200;
		const data = new Uint8ClampedArray(w * h * 4);
		for (let i = 0; i < w * h; i++) {
			const o = i * 4;
			data[o] = data[o + 1] = data[o + 2] = 250;
			data[o + 3] = 255;
		}
		// Ink must cover MORE THAN HALF the page, or a global median would also call
		// it light and the test would not discriminate. 160x160 of 200x200 is 64%, and
		// it stops short of the 20px corner patches on every side.
		for (let y = 20; y < 180; y++) {
			for (let x = 20; x < 180; x++) {
				const o = (y * w + x) * 4;
				data[o] = data[o + 1] = data[o + 2] = 0;
			}
		}
		expect(backgroundIsDark({ width: w, height: h, data } as ImageData)).toBe(false);
	});

	/**
	 * The sentinel case. `lower` used 0 for both "not found yet" and a legal luma of
	 * 0, so on a page whose lower order statistic is genuinely black the sentinel
	 * never cleared and the median came back half a level high — enough to land on
	 * the wrong side of the 128 threshold and read an inverted scan as a light page.
	 */
	it('a page whose corners are half black reads as dark', () => {
		// Left half black, right half white. Two corner patches are pure 0 and two are
		// pure 255, so the lower order statistic is exactly 0 and the true median is
		// 127.5 — just below the threshold.
		const w = 200;
		const h = 200;
		const data = new Uint8ClampedArray(w * h * 4);
		for (let y = 0; y < h; y++) {
			for (let x = 0; x < w; x++) {
				const o = (y * w + x) * 4;
				const v = x < w / 2 ? 0 : 255;
				data[o] = data[o + 1] = data[o + 2] = v;
				data[o + 3] = 255;
			}
		}
		expect(backgroundIsDark({ width: w, height: h, data } as ImageData)).toBe(true);
	});

	it('a degenerate image is not called dark', () => {
		expect(
			backgroundIsDark({ width: 0, height: 0, data: new Uint8ClampedArray(0) } as ImageData)
		).toBe(false);
	});

	/**
	 * The defect, demonstrated. On a dark page the projection profile measures the
	 * BACKGROUND as ink, so the bands it returns are the gaps between lines — and
	 * inverting afterwards, per tile, cannot undo that.
	 */
	it('segmentation finds text not gaps on a dark page', () => {
		const band: [number, number] = [80, 120];
		const dark = page(200, 200, 20, 240, band);

		// Un-normalised: whatever it finds, it is not the one band of text.
		const before = segmentLines(dark);

		const normalised = page(200, 200, 20, 240, band);
		expect(normalizePagePolarity(normalised)).toBe(true);
		const after = segmentLines(normalised);

		expect(after.length).toBeGreaterThan(0);
		// The text band is covered by a returned segment.
		const mid = (band[0] + band[1]) / 2;
		const covers = after.some((s) => s.y <= mid && s.y + s.height >= mid);
		expect(covers).toBe(true);
		// And the two differ, which is the whole point of doing it before segmenting.
		expect(JSON.stringify(before)).not.toBe(JSON.stringify(after));
	});
});

/**
 * `mergeRuns`, on the cases that were measured rather than on invented ones.
 *
 * The same cases exist in `apps/android/.../LineSegmenterTest.kt` and in iOS
 * `LineMergeTests.swift`. Written as a matching set on purpose: the defect this
 * pass exists to stop is one algorithm's four ports drifting apart unnoticed, and
 * a divergence is far easier to see in test files meant to read identically.
 *
 * The fixtures are NOT copies of `monocr-onnx` `rust/src/segmenter.rs`, and that
 * is deliberate. Three of the Rust fixtures are degenerate against the mutation
 * they are named for, because with only two runs on the page the median run
 * height IS one of the two:
 *
 *   - its ink-alone case has runs of 40, 40, 82, 82, so the median is 82 and
 *     `2 * 40 <= 82` makes the fragment clause fire too — dropping the ink clause
 *     survives it;
 *   - its wide-gap case has two runs of 40, so the ceiling is 80 and the merged
 *     span would be 95 — the ceiling refuses it and dropping the size bound
 *     survives;
 *   - its two-lines-apart case is refused by the same ceiling, so weakening the
 *     fragment ratio from 2x to 1x survives.
 *
 * Every fixture below therefore carries ordinary full-height lines as well as the
 * pair under test, which puts the median where a real page would put it. All
 * three mutations die here. Verified by running them.
 *
 * These pass the RAW profile, which in this module is `rawHist` — `hist` is the
 * smoothed one, inverted from every other port's naming.
 */
describe('mergeRuns', () => {
	/** A profile with the given [start, end) ranges filled to `value`. */
	function profile(length: number, fills: [number, number, number][]): Float32Array {
		const h = new Float32Array(length);
		for (const [a, b, v] of fills) h.fill(v, a, b);
		return h;
	}

	it('a sub-threshold dip does not end a line', () => {
		// The measured case, in the reference's numbers: one line, rows 260-324,
		// split by row 280 carrying 6 ink pixels against a threshold of 7.0. On this
		// port the same shape is a dip row of 12 ink columns against 15.60.
		const hist = profile(400, [[260, 325, 200]]);
		hist[280] = 6; // above zero, below the gap threshold
		expect(
			mergeRuns(
				[
					[260, 280],
					[281, 325]
				],
				hist,
				10
			)
		).toEqual([[260, 325]]);
	});

	it('a zero-ink gap still merges a fragment into its line', () => {
		// The other measured case: rows 341-360 are the upper marks and 362-404 the
		// body of one line, separated by TWO rows of genuinely zero ink. The ink
		// clause cannot cross that; the height ratio is what does.
		const hist = profile(500, [
			[341, 360, 40],
			[362, 404, 300]
		]);
		expect(
			mergeRuns(
				[
					[341, 360],
					[362, 404]
				],
				hist,
				10
			)
		).toEqual([[341, 404]]);
	});

	it('two real lines two rows apart stay separate', () => {
		// The case the fragment clause must NOT swallow, and the reason it is a
		// ratio: same gap, same emptiness, but both runs are full height against the
		// page median. A vertical smear was tried instead and fused exactly this
		// pair, which is why the fix is not a smear.
		const hist = profile(400, [
			[20, 60, 300],
			[62, 102, 300],
			[150, 210, 300],
			[260, 320, 300]
		]);
		expect(
			mergeRuns(
				[
					[20, 60],
					[62, 102],
					[150, 210],
					[260, 320]
				],
				hist,
				10
			)
		).toEqual([
			[20, 60],
			[62, 102],
			[150, 210],
			[260, 320]
		]);
	});

	it('a wide gap is a line boundary however much ink it holds', () => {
		// The size bound on its own. Overlapping diacritics can hold the raw profile
		// above zero right across real inter-line spacing; upstream that collapsed 3
		// PDF lines into 1. The two 60-row lines put the ceiling at 120, above the
		// 95-row span a merge here would produce, so the size bound is the only thing
		// refusing it.
		const hist = profile(400, [
			[20, 60, 300],
			[60, 75, 5], // 15 rows of ink between two lines
			[75, 115, 300],
			[200, 260, 300],
			[300, 360, 300]
		]);
		expect(
			mergeRuns(
				[
					[20, 60],
					[75, 115],
					[200, 260],
					[300, 360]
				],
				hist,
				10
			)
		).toEqual([
			[20, 60],
			[75, 115],
			[200, 260],
			[300, 360]
		]);
	});

	it('a dip between equal halves merges on the ink clause alone', () => {
		// The ink clause isolated. In the dip case above the fragment clause ALSO
		// fires, so dropping `gapHasInk` survives it. Here the two halves are 40 rows
		// against a page median of 60, so `2 * 40 <= 60` is false and only the ink
		// test can merge them.
		const hist = profile(400, [
			[20, 60, 300],
			[60, 62, 5], // two rows of ink: below any threshold, above zero
			[62, 102, 300],
			[150, 210, 300],
			[260, 320, 300]
		]);
		expect(
			mergeRuns(
				[
					[20, 60],
					[62, 102],
					[150, 210],
					[260, 320]
				],
				hist,
				10
			)
		).toEqual([
			[20, 102],
			[150, 210],
			[260, 320]
		]);
	});

	it('a run of fragments cannot chain past twice a typical line', () => {
		// The ceiling and the median, together, on the failure they exist for. Five
		// 20-row fragments two empty rows apart would chain into one 108-row band,
		// and this is the shape that cost 92% of a real page's characters when the
		// fragment test compared against the NEIGHBOUR instead of the median: every
		// merge makes the accumulated run taller, and a taller run makes the next
		// line look more like a fragment.
		//
		// Against a page median of 45 the ceiling is 90, so the chain stops after
		// four. Judging against the neighbour merges nothing here at all, so this
		// case pins both halves of the correction.
		const fills: [number, number, number][] = [
			[0, 20, 200],
			[22, 42, 200],
			[44, 64, 200],
			[66, 86, 200],
			[88, 108, 200]
		];
		const lines: [number, number][] = [];
		for (let i = 0; i < 5; i++) {
			const y = 200 + i * 100;
			fills.push([y, y + 45, 300]);
			lines.push([y, y + 45]);
		}
		const hist = profile(700, fills);
		expect(
			mergeRuns([[0, 20], [22, 42], [44, 64], [66, 86], [88, 108], ...lines], hist, 10)
		).toEqual([[0, 86], [88, 108], ...lines]);
	});

	it('leaves an empty page alone', () => {
		expect(mergeRuns([], new Float32Array(10), 10)).toEqual([]);
	});
});

/**
 * The merge must be reached THROUGH `segmentLines`, not only unit-tested.
 *
 * In the Rust port a mutation that deleted the `merge_runs` call from the
 * pipeline SURVIVED all four helper tests, because they call the helper directly
 * and the call site was unguarded. That is the gap `se-brain`
 * `rules/standards/testing.md` §23 names: a tested helper does not make its call
 * site safe.
 *
 * Geometry is this port's measured one. Rust's is not reusable here: this port
 * dilates the mask vertically with reach 2 before the profile, so a source gap
 * under 5 rows never reaches the profile at all, and 5 rows is the tightest gap
 * that still splits.
 */
describe('a diacritic strip comes back joined to its line', () => {
	/**
	 * A page of Mon-shaped lines: a sparse strip of upper marks, `gap` source rows,
	 * then a solid consonant body.
	 *
	 * Sparse marks, not a solid bar. The segmenter binarizes against a 25px local
	 * mean, so the inside of a solid bar is not darker than its own neighbourhood
	 * and only its edges register as ink — the same reason the Android fixtures draw
	 * strokes. Words rather than a full-width ribbon, because a ribbon this wide
	 * reads as a printed rule and `suppressPageRules` removes it.
	 */
	function monPage(gap: number, lines: number): ImageData {
		const w = 900;
		const h = 1200;
		const data = new Uint8ClampedArray(w * h * 4).fill(255);
		const ink = (x: number, y: number) => {
			const i = (y * w + x) * 4;
			data[i] = data[i + 1] = data[i + 2] = 0;
		};
		const STRIP_H = 20;
		const BODY_H = 45;
		for (let l = 0; l < lines; l++) {
			const y0 = 100 + l * 100;
			const bodyStart = y0 + STRIP_H + gap;
			let g = 0;
			for (let x = 60; x < w - 60; x += 6, g++) {
				if ((x - 60) % 60 >= 42) continue; // word spacing
				for (let y = bodyStart; y < bodyStart + BODY_H; y++) {
					ink(x, y);
					ink(x + 1, y);
				}
				if (g % 3 === 0) {
					for (let y = y0; y < y0 + STRIP_H; y++) {
						ink(x, y);
						ink(x + 1, y);
					}
				}
			}
		}
		return { width: w, height: h, data } as ImageData;
	}

	it('a zero-ink gap: 10 lines come back as 10 bands, not 20', () => {
		// Measured on this port before the merge existed: 20 bands, every line cut
		// into a strip of glyph tops and a decapitated body.
		const bands = segmentLines(monPage(5, 10));

		expect(bands.length).toBe(10);
		// And each band spans the marks AND the body, not just one of them. The
		// drawn line box is 70 source rows; dilation and 25% padding make the band
		// taller than that, and a body-only band would be 75px.
		for (const b of bands) expect(b.height).toBeGreaterThan(100);
	});

	it('a 4-row gap is closed by the dilation, so the merge changes nothing', () => {
		// The control. Below 5 source rows the vertical smear bridges the gap before
		// the profile sees it, so this case never reached `mergeRuns` and must still
		// return the drawn count.
		expect(segmentLines(monPage(4, 10)).length).toBe(10);
	});
});
